api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: [ 'application/json' ]
        jsonsafe: [ 'application/json+safe' ]
        html: [ 'text/html' ]
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
        enable_swagger: true
        enable_swagger_ui: true
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
